include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter (experimental): true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    diagnostic_describe_all_properties: true
    empty_statements: true
    hash_and_equals: true
    invariant_booleans (experimental): true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_relative_imports: false
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    use_key_in_widget_constructors: true
    valid_regexps: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: false
    always_require_non_null_named_parameters: true
    always_specify_types: false
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_as: false
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: false
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: true
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    file_names: true
    flutter_style_todos: true
    implementation_imports: true
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    lines_longer_than_80_chars: false
    missing_whitespace_between_adjacent_strings: true
    no_runtimeType_toString: true
    non_constant_identifier_names: true
    null_closures: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_bool_in_asserts (deprecated): true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_double_quotes: false
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_in_for_each: false
    prefer_final_locals: false
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    public_member_api_docs: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    super_goes_last (deprecated): true
    type_annotate_public_apis: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_final: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    void_checks: true
    package_names: true
    abstract_super_member_reference: true
    ambiguous_extension_member_access: true
    ambiguous_import: true
    ambiguous_set_or_map_literal_both: true
    ambiguous_set_or_map_literal_either: true
    argument_type_not_assignable: true
    assignment_to_final: true
    assignment_to_final_local: true
    assignment_to_final_no_setter: true
    assignment_to_method: true
    built_in_identifier_as_extension_name: true
    built_in_identifier_as_type: true
    case_block_not_terminated: true
    cast_to_non_type: true
    concrete_class_with_abstract_member: true
    const_constructor_with_non_final_field: true
    const_initialized_with_non_constant_value: true
    const_instance_field: true
    const_not_initialized: true
    const_spread_expected_list_or_set: true
    const_spread_expected_map: true
    const_with_non_const: true
    const_with_non_constant_argument: true
    dead_code: true
    dead_code_catch_following_catch: true
    dead_code_on_catch_subtype: true
    deprecated_member_use: true
    deprecated_member_use_from_same_package: true
    duplicate_constructor: true
    duplicate_definition: true
    duplicate_import: true
    duplicate_named_argument: true
    equal_elements_in_const_set: true
    equal_keys_in_const_map: true
    expression_in_map: true
    extends_non_class: true
    extension_as_expression: true
    extension_conflicting_static_and_instance: true
    extension_declares_abstract_member: true
    extension_declares_constructor: true
    extension_declares_instance_field: true
    extension_declares_member_of_object: true
    extension_override_access_to_static_member: true
    extension_override_argument_not_assignable: true
    extension_override_without_access: true
    extension_override_with_cascade: true
    extra_positional_arguments: true
    extra_positional_arguments_could_be_named: true
    final_not_initialized: true
    final_not_initialized_constructor: true
    for_in_of_invalid_type: true
    implements_non_class: true
    implements_repeated: true
    implicit_this_reference_in_initializer: true
    initializer_for_non_existent_field: true
    initializing_formal_for_non_existent_field: true
    instance_access_to_static_member: true
    instance_member_access_from_factory: true
    instance_member_access_from_static: true
    instantiate_abstract_class: true
    invalid_assignment: true
    invalid_extension_argument_count: true
    invalid_factory_name_not_a_class: true
    invalid_literal_annotation: true
    invalid_override: true
    invalid_reference_to_this: true
    invalid_uri: true
    invalid_use_of_covariant_in_extension: true
    invalid_visibility_annotation: true
    invocation_of_extension_without_call: true
    invocation_of_non_function: true
    invocation_of_non_function_expression: true
    list_element_type_not_assignable: true
    map_entry_not_in_map: true
    map_key_type_not_assignable: true
    map_value_type_not_assignable: true
    missing_enum_constant_in_switch: true
    missing_required_param: true
    missing_return: true
    mixin_of_non_class: true
    mixin_on_sealed_class: true
    mixin_super_class_constraint_non_interface: true
    must_be_immutable: true
    must_call_super: true
    new_with_undefined_constructor_default: true
    non_abstract_class_inherits_abstract_member: true
    non_bool_condition: true
    non_bool_expression: true
    non_bool_negation_expression: true
    non_bool_operand: true
    non_constant_case_expression: true
    non_constant_default_value: true
    non_constant_list_element: true
    non_constant_map_element: true
    non_constant_map_key: true
    non_constant_map_value: true
    non_constant_set_element: true
    non_const_call_to_literal_constructor: true
    non_type_as_type_argument: true
    non_type_in_catch_clause: true
    not_a_type: true
    not_enough_positional_arguments: true
    not_iterable_spread: true
    not_map_spread: true
    no_annotation_constructor_arguments: true
    override_on_non_overriding_member: true
    part_of_non_part: true
    redirect_to_invalid_function_type: true
    redirect_to_invalid_return_type: true
    redirect_to_non_class: true
    referenced_before_declaration: true
    return_of_invalid_type: true
    return_of_invalid_type_from_closure: true
    return_without_value: true
    sdk_version_async_exported_from_core: true
    sdk_version_as_expression_in_const_context: true
    sdk_version_bool_operator_in_const_context: true
    sdk_version_eq_eq_operator_in_const_context: true
    sdk_version_extension_methods: true
    sdk_version_is_expression_in_const_context: true
    sdk_version_set_literal: true
    sdk_version_ui_as_code: true
    sdk_version_ui_as_code_in_const_context: true
    static_access_to_instance_member: true
    super_in_extension: true
    super_in_invalid_context: true
    type_argument_not_matching_bounds: true
    type_test_with_undefined_name: true
    undefined_annotation: true
    undefined_class: true
    undefined_constructor_in_initializer: true
    undefined_extension_getter: true
    undefined_extension_method: true
    undefined_extension_setter: true
    undefined_function: true
    undefined_getter: true
    undefined_hidden_name: true
    undefined_identifier: true
    undefined_method: true
    undefined_named_parameter: true
    undefined_operator: true
    undefined_prefixed_name: true
    undefined_setter: true
    undefined_shown_name: true
    undefined_super_method: true
    unnecessary_cast: true
    unqualified_reference_to_static_member_of_extended_type: true
    unused_catch_clause: true
    unused_catch_stack: true
    unused_element: true
    unused_field: true
    unused_import: true
    unused_label: true
    unused_local_variable: true
    unused_shown_name: true
    uri_does_not_exist: true
    uri_has_not_been_generated: true
    use_of_void_result: true
    variable_type_mismatch: true
    wrong_number_of_parameters_for_operator: true
    wrong_number_of_parameters_for_setter: true
    wrong_number_of_type_arguments: true
